// Generated by LiveScript 1.6.0
(function(){
  (function(it){
    return module.exports = it;
  })(function(backend){
    var db, config, api, session, express, lderror, re2js, curegex, suuid, aux, throttle, route, reEmail, isEmail;
    db = backend.db, config = backend.config, api = backend.route.api, session = backend.session;
    if (config.base !== 'base') {
      return;
    }
    express = require('express');
    lderror = require('lderror');
    re2js = require('re2js');
    curegex = require('curegex');
    suuid = require('@plotdb/suuid');
    aux = require('@servebase/backend/aux');
    throttle = require('@servebase/backend/throttle');
    route = aux.routecatch(express.Router({
      mergeParams: true
    }));
    api.use('/admin', route);
    route.use(aux.isAdmin);
    route.get('/cachestamp', function(req, res, next){
      return res.send(backend.cachestamp + "");
    });
    route.post('/cachestamp', function(req, res, next){
      backend.cachestamp = new Date().getTime();
      return res.send(backend.cachestamp + "");
    });
    route.get('/throttle/reset', function(req, res, next){
      throttle.reset();
      return res.send();
    });
    route.post('/users/', function(req, res, next){
      var keyword;
      if (!(keyword = req.body.keyword)) {
        return lderror.reject(400);
      }
      return db.query("select u.*\nfrom users as u\nwhere (u.username = $1 or u.key = $2) and u.deleted is not true\norder by u.createdtime desc", [
        keyword, isNaN(+keyword)
          ? null
          : +keyword
      ]).then(function(r){
        var rows;
        r == null && (r = {});
        rows = r.rows || (r.rows = []);
        rows.map(function(it){
          var ref$;
          return ref$ = it.password, delete it.password, ref$;
        });
        return res.send(rows);
      });
    });
    reEmail = curegex.tw.get('email', re2js.RE2JS);
    isEmail = function(it){
      return reEmail.exec(it);
    };
    route.post('/user/delete', function(req, res){
      var username;
      if (!(username = req.body.username)) {
        return lderror.reject(400);
      }
      if (!isEmail(username)) {
        return lderror.reject(400);
      }
      return backend.auth.user['delete']({
        username: username
      }).then(function(){
        return res.send({});
      });
    });
    route.post('/user/', function(req, res){
      var ref$, username, displayname, password, detail, config, method;
      if (['username', 'displayname', 'password'].filter(function(it){
        return !req.body[it];
      }).length) {
        return lderror.reject(400);
      }
      ref$ = req.body, username = ref$.username, displayname = ref$.displayname, password = ref$.password;
      if (!isEmail(username)) {
        return lderror.reject(400);
      }
      if (password.length < 8) {
        return lderror.reject(400);
      }
      detail = {
        username: username,
        displayname: displayname
      };
      config = {
        authinfo: {
          renewpw: true
        }
      };
      method = 'local';
      return db.userStore.create({
        username: username,
        password: password,
        method: method,
        detail: detail,
        config: config
      }).then(function(it){
        delete it.password;
        return res.send(it);
      });
    });
    route.post('/user/:key/password', aux.validateKey, function(req, res){
      var key, password;
      key = +req.params.key;
      if (!(password = req.body.password) || password.length < 8) {
        return lderror.reject(400);
      }
      return db.query("select password from users where key = $1", [key]).then(function(arg$){
        var rows;
        rows = arg$.rows;
        if (!rows || !rows[0]) {
          return lderror.reject(404);
        }
      }).then(function(){
        return db.userStore.hashing(password, true, true);
      }).then(function(pwHashed){
        return db.query("update users set (method,password) = ('local',$1) where key = $2", [pwHashed, key]);
      }).then(function(){
        return session['delete']({
          user: key
        });
      }).then(function(){
        return res.send();
      });
    });
    route.post('/user/:key/email', aux.validateKey, function(req, res){
      var key, email;
      key = +req.params.key;
      if (!((email = req.body.email) && isEmail(email))) {
        return lderror.reject(400);
      }
      return db.query("select key from users where username = $1", [email]).then(function(r){
        r == null && (r = {});
        if ((r.rows || (r.rows = [])).length) {
          return lderror.reject(1011);
        }
        return db.query("update users set username = $1 where key = $2", [email, key]);
      }).then(function(){
        return session['delete']({
          user: key
        });
      }).then(function(){
        return res.send();
      });
    });
    route.post('/user/:key/logout', aux.validateKey, function(req, res){
      return session['delete']({
        user: +req.params.key
      }).then(function(){
        return res.send();
      });
    });
    route['delete']('/user/:key', aux.validateKey, function(req, res, next){
      var key;
      key = +req.params.key;
      return session['delete']({
        user: key
      }).then(function(){
        return db.query("delete from users where key = $1", [key]);
      })['catch'](function(){
        return db.query("update users\nset (username,displayname,deleted)\n= (('deleted-' || key),('user ' || key),true)\nwhere key = $1", [key]);
      }).then(function(){
        return res.send();
      });
    });
    route.put('/su/:key', aux.validateKey, function(req, res){
      var key;
      key = +req.params.key;
      return session.login({
        user: key,
        req: req
      }).then(function(){
        return res.send();
      });
    });
    return route.post('/invite-token', function(req, res){
      var detail, token;
      detail = {
        count: (req.body || {}).count || 1,
        used: 0
      };
      token = (req.body || {}).token || suuid();
      return db.query("select key from invitetoken where token = $1 and deleted is not true", [token]).then(function(r){
        r == null && (r = {});
        if ((r.rows || (r.rows = [])).length) {
          return lderror.reject(1011);
        }
        return db.query("insert into invitetoken (owner,token,detail)\nvalues ($1, $2, $3) returning token", [req.user.key, token, detail]);
      }).then(function(){
        return res.send({
          token: token
        });
      });
    });
  });
}).call(this);
