// Generated by LiveScript 1.6.0
(function(){
  var fs, path, config, colors, jsYaml, lderror, re2js, curegex, jsdom, dompurify, nodemailer, nodemailerMailgunTransport, md, jsdomDoc, jsdomOption, dom, purify, reEmail, isEmail, libdir, rootdir, mailQueue;
  fs = require('fs');
  path = require('path');
  config = require('@servebase/config');
  colors = require('@plotdb/colors');
  jsYaml = require('js-yaml');
  lderror = require('lderror');
  re2js = require('re2js');
  curegex = require('curegex');
  jsdom = require('jsdom');
  dompurify = require('dompurify');
  nodemailer = require('nodemailer');
  nodemailerMailgunTransport = require('nodemailer-mailgun-transport');
  md = require('./utils/md');
  jsdomDoc = "<DOCTYPE html><html><body></body></html>";
  jsdomOption = {
    url: 'http://localhost'
  };
  dom = new jsdom.JSDOM(jsdomDoc, jsdomOption);
  purify = dompurify(new jsdom.JSDOM('').window);
  reEmail = curegex.tw.get('email', re2js.RE2JS);
  isEmail = function(it){
    return reEmail.exec(it);
  };
  libdir = path.dirname(fs.realpathSync(__filename.replace(/\(js\)$/, '')));
  rootdir = path.join(libdir, '../..');
  mailQueue = function(opt){
    var p, err, this$ = this;
    opt == null && (opt = {});
    this.api = opt.smtp
      ? nodemailer.createTransport(opt.smtp)
      : opt.mailgun
        ? nodemailer.createTransport(nodemailerMailgunTransport(opt.mailgun))
        : {
          sendMail: function(){
            this$.log.error("sendMail called while mail gateway is not available");
            return lderror.reject(500, "mail service not available");
          }
        };
    this.i18n = opt.i18n;
    this.suppress = opt.suppress;
    this.base = opt.base || 'base';
    this.log = opt.logger;
    this.info = opt.info || {};
    this.cfg = opt || {};
    if (opt.blacklist != null) {
      if (Array.isArray(opt.blacklist)) {
        this._blacklist = opt.blacklist.map(function(n){
          return ((!n
            ? ''
            : /@/.exec(n)
              ? n
              : "@" + n) + "").trim();
        }).filter(function(it){
          return it;
        });
      } else if (typeof opt.blacklist === 'object') {
        if (typeof opt.blacklist.module === 'string') {
          try {
            p = !/^\./.exec(opt.blacklist.module)
              ? opt.blacklist.module
              : path.join(rootdir, opt.blacklist.module);
            this._blacklist = require(p);
          } catch (e$) {
            err = e$;
            this.log.error({
              err: err
            }, "blacklist is provided as a module, however failed to load, and thus disabled.");
          }
        }
      }
    }
    this.list = [];
    return this;
  };
  mailQueue.prototype = import$(Object.create(Object.prototype), {
    inBlacklist: function(m){
      var this$ = this;
      m == null && (m = "");
      return !this._blacklist
        ? Promise.resolve(false)
        : Array.isArray(this._blacklist)
          ? Promise.resolve().then(function(){
            var i$, i;
            for (i$ = this$._blacklist.length - 1; i$ >= 0; --i$) {
              i = i$;
              if (~m.indexOf(this$._blacklist[i])) {
                return true;
              }
            }
            return false;
          })
          : typeof this._blacklist.is === 'function'
            ? this._blacklist.is(m)
            : Promise.resolve(false);
    },
    add: function(obj){
      this.list.push(obj);
      return this.handler();
    },
    handle: null,
    handler: function(){
      var this$ = this;
      if (this.handle) {
        return;
      }
      this.log.info("new job incoming, handling...".cyan);
      return this.handle = setInterval(function(){
        var obj;
        this$.log.info((this$.list.length + " jobs remain...").cyan);
        obj = this$.list.splice(0, 1)[0];
        if (!obj) {
          this$.log.info("all job done, take a rest.".green);
          clearInterval(this$.handle);
          this$.handle = null;
          return;
        }
        return this$.sendDirectly(obj.payload).then(obj.res)['catch'](obj.rej);
      }, 5000);
    },
    send: function(payload, opt){
      var this$ = this;
      opt == null && (opt = {});
      if (opt.from) {
        payload.from = opt.from;
      }
      if (opt.cc) {
        payload.cc = opt.cc;
      }
      if (opt.bcc) {
        payload.bcc = opt.bcc;
      }
      if (opt.now) {
        return this.sendDirectly(payload);
      }
      return new Promise(function(res, rej){
        return this$.add({
          payload: payload,
          res: res,
          rej: rej
        });
      });
    },
    sendDirectly: function(payload){
      var this$ = this;
      return new Promise(function(res, rej){
        var cc, bcc;
        cc = !payload.cc
          ? ' '
          : " [cc:" + (Array.isArray(payload.cc)
            ? payload.cc.join(' ')
            : payload.cc) + "] ";
        bcc = !payload.bcc
          ? ''
          : "[bcc:" + (Array.isArray(payload.bcc)
            ? payload.bcc.join(' ')
            : payload.bcc) + "] ";
        if (payload.html) {
          payload.html = purify.sanitize(payload.html);
        }
        this$.log.info(((this$.suppress ? '(suppressed)'.gray : '') + " sending [from:" + payload.from + "] [to:" + payload.to + "]" + cc + bcc + "[subject:" + payload.subject + "]").cyan);
        if (this$.suppress) {
          return res();
        }
        return this$.api.sendMail(payload, function(err, i){
          if (!err) {
            return res();
          }
          this$.log.error({
            err: err
          }, "send mail failed: api.sendMail failed.");
          return res();
        });
      });
    },
    sendFromMd: function(payload, map, opt){
      var this$ = this;
      map == null && (map = {});
      opt == null && (opt = {});
      return this.getContent({
        payload: payload,
        map: map,
        lng: opt.lng
      }).then(function(payload){
        return this$.send(payload, {
          now: opt.now,
          from: opt.from,
          cc: opt.cc,
          bcc: opt.bcc
        });
      });
    },
    byTemplate: function(name, email, map, opt){
      var this$ = this;
      map == null && (map = {});
      opt == null && (opt = {});
      return this.getContent({
        name: name,
        map: map,
        lng: opt.lng
      }).then(function(payload){
        return this$.send((payload.to = email, payload), {
          now: opt.now,
          from: opt.from,
          cc: opt.cc,
          bcc: opt.bcc
        });
      })['catch'](function(err){
        this$.log.error({
          err: err
        }, "send mail by template failed for name `" + name + "`");
        return Promise.reject(err);
      });
    },
    getContent: function(arg$){
      var name, payload, map, lng, this$ = this;
      name = arg$.name, payload = arg$.payload, map = arg$.map, lng = arg$.lng;
      return Promise.resolve().then(function(){
        if (!name) {
          return JSON.parse(JSON.stringify(payload || {}));
        }
        return config.yaml(['private', this$.base, 'base'].map(function(it){
          return path.join(it, "mail/" + name + ".yaml");
        }), lng);
      }).then(function(payload){
        var content, k, ref$, v, re;
        payload == null && (payload = {});
        if (!(content = payload.content || '')) {
          return payload;
        }
        for (k in ref$ = map) {
          v = ref$[k];
          re = new RegExp("#{" + k + "}", "g");
          content = content.replace(re, v);
          payload.from = (payload.from || '').replace(re, v);
          payload.subject = (payload.subject || '').replace(re, v);
        }
        payload.text = md.toText(content);
        payload.html = md.toHtml(content);
        return payload;
      }).then(function(payload){
        payload.html = purify.sanitize(payload.html || '');
        return payload;
      });
    },
    batch: function(arg$){
      var sender, recipients, name, payload, params, batchSize, lng, batch, ref$, ps, this$ = this;
      sender = arg$.sender, recipients = arg$.recipients, name = arg$.name, payload = arg$.payload, params = arg$.params, batchSize = arg$.batchSize, lng = arg$.lng;
      sender = this.cfg.defaultSender || sender;
      if (!sender && !(this.cfg.sitename && this.cfg.domain)) {
        return lderror.reject(1015);
      }
      if (!sender) {
        sender = "\"" + this.i18n.t(this.cfg.sitename, {
          lng: lng
        }) + "\" <no-reply@" + this.cfg.domain + ">";
      }
      batch = [];
      params = (ref$ = params || {}, ref$.domain = this.cfg.domain, ref$.sitename = this.i18n.t(this.cfg.sitename, {
        lng: lng
      }), ref$);
      payload = (ref$ = import$({}, payload || {}), ref$.from = sender, ref$);
      batchSize = batchSize || 1;
      recipients = (recipients || []).map(function(it){
        return it;
      }).filter(function(it){
        return isEmail(it);
      });
      if (!recipients.length) {
        return Promise.resolve();
      }
      if (!(name || payload.subject)) {
        return Promise.resolve();
      }
      while (recipients.length) {
        batch.push(recipients.splice(0, batchSize));
      }
      ps = batch.map(function(rs){
        var _payload, e;
        rs == null && (rs = []);
        try {
          _payload = JSON.parse(JSON.stringify(payload));
        } catch (e$) {
          e = e$;
          return Promise.reject(e);
        }
        if (!rs.length) {
          return Promise.resolve();
        }
        return Promise.resolve().then(function(){
          var ref$;
          import$(_payload, rs.length > 1
            ? {
              to: sender,
              bcc: rs
            }
            : {
              to: rs
            });
          if (name && !(_payload.subject && (_payload.text || payload.html))) {
            return this$.byTemplate(name, _payload.to, params, (ref$ = {
              lng: lng,
              now: true
            }, ref$.from = _payload.from, ref$.bcc = _payload.bcc, ref$));
          }
          return this$.send(_payload);
        });
      });
      return Promise.all(ps);
    }
  });
  module.exports = mailQueue;
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
